In [2]:
from keras.datasets import imdb
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer

In [4]:
import re
def rm_tags(text):
    re_tag = re.compile(r'<[^>]+>')
    return re_tag.sub('', text)

In [5]:
import os
def read_files(filetype):
    path = "C:/Users/ken09/Desktop/data/aclImdb_v1/aclImdb/"
    file_list=[]
    
    positive_path=path + filetype+"/pos/"
    for f in os.listdir(positive_path):
        file_list+=[positive_path+f]
        
    negative_path=path + filetype+"/neg/"
    for f in os.listdir(negative_path):
        file_list+=[negative_path+f]
        
    print('read',filetype, 'files:', len(file_list))
    
    all_labels = ([1] * 12500 + [0] * 12500)
    
    all_texts = []
    for fi in file_list:
        with open(fi, encoding = 'utf8') as file_input:
            all_texts += [rm_tags(" ".join(file_input.readlines()))]
            
    return all_labels,all_texts

In [6]:
y_train,train_text=read_files("train")

read train files: 25000


In [7]:
y_test,test_text=read_files("test")

read test files: 25000


In [48]:
token = Tokenizer(num_words=3800)
token.fit_on_texts(train_text)

In [49]:
x_train_seq = token.texts_to_sequences(train_text)
x_test_seq = token.texts_to_sequences(test_text)

In [50]:
x_train = sequence.pad_sequences(x_train_seq, maxlen=380)
x_test = sequence.pad_sequences(x_test_seq, maxlen=380)

In [74]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation,Flatten
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM

In [75]:
model = Sequential()

In [76]:
model.add(Embedding(output_dim=32,input_dim=3800,input_length=380))
model.add(Dropout(0.2))

In [77]:
model.add(LSTM(32))

In [78]:
model.add(Dense(units=256,activation='relu'))
model.add(Dropout(0.2))

In [79]:
model.add(Dense(units=1,activation='sigmoid'))

In [80]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 380, 32)           121600    
_________________________________________________________________
dropout_8 (Dropout)          (None, 380, 32)           0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_7 (Dense)              (None, 256)               8448      
_________________________________________________________________
dropout_9 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 257       
Total params: 138,625
Trainable params: 138,625
Non-trainable params: 0
_________________________________________________________________


In [81]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [82]:
train_history = model.fit(x_train,y_train,batch_size=100,epochs=10,verbose=2,validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
 - 62s - loss: 0.5262 - acc: 0.7327 - val_loss: 0.4866 - val_acc: 0.7504
Epoch 2/10
 - 58s - loss: 0.3106 - acc: 0.8689 - val_loss: 0.5292 - val_acc: 0.7756
Epoch 3/10
 - 58s - loss: 0.2471 - acc: 0.9032 - val_loss: 0.5495 - val_acc: 0.7424
Epoch 4/10
 - 59s - loss: 0.2229 - acc: 0.9141 - val_loss: 0.3960 - val_acc: 0.8210
Epoch 5/10
 - 58s - loss: 0.1991 - acc: 0.9267 - val_loss: 0.3461 - val_acc: 0.8358
Epoch 6/10
 - 59s - loss: 0.1896 - acc: 0.9280 - val_loss: 0.7475 - val_acc: 0.7442
Epoch 7/10
 - 59s - loss: 0.1601 - acc: 0.9405 - val_loss: 0.6244 - val_acc: 0.7446
Epoch 8/10
 - 58s - loss: 0.1367 - acc: 0.9524 - val_loss: 0.5269 - val_acc: 0.8170
Epoch 9/10
 - 59s - loss: 0.1212 - acc: 0.9590 - val_loss: 0.6272 - val_acc: 0.7948
Epoch 10/10
 - 59s - loss: 0.1146 - acc: 0.9604 - val_loss: 0.5419 - val_acc: 0.8206


In [83]:
scores = model.evaluate(x_test, y_test, verbose=1)
scores[1]

25000/25000 [==============================] - 31s 1ms/step


0.85572

In [22]:
predict=model.predict_classes(x_test)

In [23]:
predict[:10]

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1]])

In [24]:
predict_classes=predict.reshape(-1)
predict_classes[:10]

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [25]:
SentimentDict={1:'正面的',0:'負面的'}
def display_test_Sentiment(i):
    print(test_text[i])
    print('label真實值:',SentimentDict[y_test[i]],'預測結果:',SentimentDict[predict_classes[i]])

In [26]:
display_test_Sentiment(2)

As a recreational golfer with some knowledge of the sport's history, I was pleased with Disney's sensitivity to the issues of class in golf in the early twentieth century. The movie depicted well the psychological battles that Harry Vardon fought within himself, from his childhood trauma of being evicted to his own inability to break that glass ceiling that prevents him from being accepted as an equal in English golf society. Likewise, the young Ouimet goes through his own class struggles, being a mere caddie in the eyes of the upper crust Americans who scoff at his attempts to rise above his standing. What I loved best, however, is how this theme of class is manifested in the characters of Ouimet's parents. His father is a working-class drone who sees the value of hard work but is intimidated by the upper class; his mother, however, recognizes her son's talent and desire and encourages him to pursue his dream of competing against those who think he is inferior.Finally, the golf scenes

In [27]:
display_test_Sentiment(12502)

First of all I hate those moronic rappers, who could'nt act if they had a gun pressed against their foreheads. All they do is curse and shoot each other and acting like cliché'e version of gangsters.The movie doesn't take more than five minutes to explain what is going on before we're already at the warehouse There is not a single sympathetic character in this movie, except for the homeless guy, who is also the only one with half a brain.Bill Paxton and William Sadler are both hill billies and Sadlers character is just as much a villain as the gangsters. I did'nt like him right from the start.The movie is filled with pointless violence and Walter Hills specialty: people falling through windows with glass flying everywhere. There is pretty much no plot and it is a big problem when you root for no-one. Everybody dies, except from Paxton and the homeless guy and everybody get what they deserve.The only two black people that can act is the homeless guy and the junkie but they're actors by 

In [35]:
input_text = '''
Many movies have been shot about the Disney cartoon "The Beauty and the Beast", but this is really the best. I adored it and I watched it many times. Emma Watson is fantastic in her role, the perfect Bella: beauty, sweet and really similar to the protagonist of the story. Also the rest of the movie is perfectly aderent to the cartoon, with some scenes full of pathos (the best one is the dance in the castle with the amazing yellow dress). If you like Disney cartoons and romantic stories, nothing comparable to this!
'''

In [36]:
input_seq = token.texts_to_sequences([input_text])

In [37]:
print(input_seq[0])

[107, 98, 24, 73, 320, 40, 1, 909, 1068, 1, 931, 2, 1, 17, 10, 6, 62, 1, 114, 9, 8, 2, 9, 292, 8, 107, 207, 6, 772, 7, 37, 213, 1, 400, 931, 1043, 2, 62, 726, 5, 1, 4, 1, 61, 77, 1, 356, 4, 1, 16, 6, 946, 5, 1, 1068, 15, 45, 135, 364, 4, 1, 114, 27, 6, 1, 832, 7, 1, 1652, 15, 1, 476, 44, 21, 36, 909, 2, 728, 533, 159, 5, 10]


In [38]:
len(input_seq[0])

82

In [39]:
pad_input_seq = sequence.pad_sequences(input_seq, maxlen=380)

In [40]:
len(input_seq[0])

82

In [41]:
predict_result=model.predict_classes(pad_input_seq)

In [42]:
predict_result

array([[1]])

In [43]:
predict_result[0][0]

1

In [44]:
SentimentDict[predict_result[0][0]]

'正面的'

In [45]:
def predict_review(input_text):
    input_seq = token.texts_to_sequences([input_text])
    pad_input_seq = sequence.pad_sequences(input_seq, maxlen=380)
    predict_result=model.predict_classes(pad_input_seq)
    print(SentimentDict[predict_result[0][0]])

In [47]:
predict_review('''
This movie was completely unnecessary. It does everything from the original animated film but in a bland and boring way. The few things added or changed had no reason to be because the story was already perfect. There was no need for a remake and it was obviously done for some quick cash. They should have just done a rerelease of the original instead of a watered down version.
''')

負面的
