In [2]:
import tensorflow as tf

In [4]:
X = tf.Variable([[0.4,0.2,0.4]])
W = tf.Variable([[-0.5,-0.2],[-0.3,0.4],[-0.5,0.2]])
b = tf.Variable([[0.1,0.2]])
XWb=tf.matmul(X,W)+b
y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:');print(sess.run(XWb))
    print('y:');print(sess.run(y))

XWb:
[[-0.35999998  0.28      ]]
y:
[[0.   0.28]]


In [5]:
X = tf.Variable([[0.4,0.2,0.4]])
W = tf.Variable([[-0.5,-0.2],[-0.3,0.4],[-0.5,0.2]])
b = tf.Variable([[0.1,0.2]])
XWb=tf.matmul(X,W)+b
y=tf.nn.sigmoid(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:');print(sess.run(XWb))
    print('y:');print(sess.run(y))

XWb:
[[-0.35999998  0.28      ]]
y:
[[0.41095957 0.5695462 ]]


In [7]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.Variable([[0.4,0.2,0.4]])

y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('b:');print(sess.run(b))
    print('W:');print(sess.run(W))
    print('y:');print(sess.run(y))

b:
[[ 0.41923225 -0.84782577]]
W:
[[-0.5265617  -0.8092731 ]
 [-0.31344312 -0.2900169 ]
 [ 2.6215496  -0.9323456 ]]
y:
[[1.1945388 0.       ]]


In [10]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.Variable([[0.4,0.2,0.4]])

y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y)=sess.run((b,W,y))
    print('b:')
    print(_b)
    print('W:')
    print(_W)
    print('y:')
    print(_y)

b:
[[-0.41709298  1.9360237 ]]
W:
[[-1.4492795  -0.74813986]
 [ 1.1528502  -0.20728326]
 [ 1.9827236   0.61646926]]
y:
[[0.02685463 1.8418988 ]]


In [11]:
ts_norm = tf.random_normal([1000])
with tf.Session() as session:
    norm_data=ts_norm.eval()
print(norm_data[:5])

[-0.41819993  2.012221   -0.59644216 -1.1253415  -1.1840594 ]


In [12]:
import matplotlib.pyplot as plt
plt.hist(norm_data)
plt.show()

<Figure size 640x480 with 1 Axes>

In [14]:
import numpy as np
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.placeholder("float",[None,3])

y=tf.nn.relu(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[.4,0.2,0.4]])
    (_b,_W,_X,_y)=sess.run((b,W,X,y),feed_dict={X:X_array})
    print('b:');print(_b)
    print('W:');print(_W)
    print('X:');print(_X)
    print('y:');print(_y)

b:
[[1.4298509  0.81713444]]
W:
[[-0.3589066  -0.75577635]
 [-0.7819709   0.37350965]
 [-0.5683563   1.36513   ]]
X:
[[0.4 0.2 0.4]]
y:
[[0.9025516 1.1355778]]


In [16]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([1,2]))
X = tf.placeholder("float",[None,3])

y=tf.nn.sigmoid(tf.matmul(X,W)+b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[.4,0.2,0.4],[0.3,0.4,0.5],[0.3,-0.4,0.5]])
    (_b,_W,_X,_y)=sess.run((b,W,X,y),feed_dict={X:X_array})
    print('b:');print(_b)
    print('W:');print(_W)
    print('X:');print(_X)
    print('y:');print(_y)

b:
[[ 0.3713075 -0.1531887]]
W:
[[ 1.1030519  -0.23890463]
 [-1.12712     1.9554288 ]
 [ 1.5098001   0.09546414]]
X:
[[ 0.4  0.2  0.4]
 [ 0.3  0.4  0.5]
 [ 0.3 -0.4  0.5]]
y:
[[0.7669242  0.54500806]
 [0.73229057 0.64680934]
 [0.8707911  0.27701846]]


In [17]:
def layer(output_dim,input_dim,inputs,activation=None):
    W = tf.Variable(tf.random_normal([input_dim,output_dim]))
    b = tf.Variable(tf.random_normal([1,output_dim]))
    XWb = tf.matmul(inputs,W) +b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs

In [19]:
X = tf.placeholder("float", [None,4])
h=layer(output_dim=3,input_dim=4,inputs=X,activation=tf.nn.relu)
y=layer(output_dim=2,input_dim=3,inputs=h)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4,0.5]])
    (layer_X,layer_h,layer_y)= \
    sess.run((X,h,y),feed_dict={X:X_array})
    print('input layer X:');print(layer_X)
    print('hidden layer h:');print(layer_h)
    print('output layer y:');print(layer_y)

input layer X:
[[0.4 0.2 0.4 0.5]]
hidden layer h:
[[2.2540812 0.        0.       ]]
output layer y:
[[-4.5802717  1.5825672]]


In [20]:
def layer_debug(output_dim,input_dim,inputs,activation=None):
    W = tf.Variable(tf.random_normal([input_dim,output_dim]))
    b = tf.Variable(tf.random_normal([1,output_dim]))
    XWb = tf.matmul(inputs,W) +b
    if activation is None:
        outputs = XWb
    else:
        outputs = activation(XWb)
    return outputs,W,b

In [21]:
X = tf.placeholder("float", [None,4])
h,W1,b1=layer_debug(output_dim=3,input_dim=4,inputs=X,activation=tf.nn.relu)
y,W2,b2=layer_debug(output_dim=2,input_dim=3,inputs=h)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2 ,0.4,0.5]])
    (layer_X,layer_h,layer_y,W1,b1,W2,b2)= \
    sess.run((X,h,y,W1,b1,W2,b2),feed_dict={X:X_array})
    print('input layer X:');print(layer_X)
    print('W1:');print( W1)
    print('b1:');print( b1)
    print('hidden layer h:');print(layer_h)
    print('W2:');print( W2)
    print('b2:');print( b2)
    print('output layer y:');print(layer_y)

input layer X:
[[0.4 0.2 0.4 0.5]]
W1:
[[ 0.140721   -0.36341292 -0.8377586 ]
 [ 1.8005847   0.01609708 -0.6909464 ]
 [ 0.8544063   0.13402656  1.9568764 ]
 [ 0.7237219   0.10750653 -0.4322356 ]]
b1:
[[ 1.9078021   0.59799856 -1.364369  ]]
hidden layer h:
[[3.027831  0.5632167 0.       ]]
W2:
[[-0.65077764  0.06291141]
 [-0.1031062   0.04046944]
 [ 2.2249868   2.1136248 ]]
b2:
[[2.2367725  0.61126393]]
output layer y:
[[0.20825672 0.82454216]]
